### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by YanDevDe** [lbgm/pro-calendar-vue#2]
Hello!

Your plugins look promising. I do wonder if you could include a license in your project to give us ideas on how to use your work?

Thank you so much, 

Yan

**Comment by lbgm** [comment]
hi @YanDevDe . i get it, i am in my holidays and i will fix this issue as soon as possible. Thank you for the reminder !

**Comment by lbgm** [comment]
hi @YanDevDe . it's done !
